server:
  port: 10000
spring:
  application:
    name: mall-coupon
  profiles:
    active: dev
  main: #springboot 2.6.0版本以上开始检查循环依赖 解决 配置如下 或者添加注解 @Lazy
    allow-circular-references: true
  datasource:
    #com.mysql.cj.jdbc.Driver是MySQL 8.0版本中的默认驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/mall-sms
    username: root
    password: root
    # HikariCP 是一个高性能的 JDBC 连接池组件
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config: # nacos 作为配置中心配置
#        namespace:
#        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import: # nacos 作为配置中心新版本配置
#      - optional:nacos:test.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
      - nacos:nacos-config.yaml #nacos-config.yaml或者 nacos-config.properties

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl