server:
  port: 10000
spring:
  application:
    name: mall-coupon
  datasource:
    #com.mysql.cj.jdbc.Driver是MySQL 8.0版本中的默认驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/mall-sms
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config: # nacos 作为配置中心配置
#        namespace:
#        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import: # nacos 作为配置中心新版本配置
#      - optional:nacos:test.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
      - nacos:nacos-config.yaml #nacos-config.yaml或者 nacos-config.properties

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl