server:
  port: 14000
spring:
  application:
    name: mall-ware
  datasource:
    #com.mysql.cj.jdbc.Driver是MySQL 8.0版本中的默认驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/mall-wms
    username: root
    password: root
    # HikariCP 是一个高性能的 JDBC 连接池组件
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        #指定文件名，没有则默认${spring.application.name}
        #指定文件后缀
        file-extension: yaml
        import-check:
          enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
