server:
  port: 13000
  #配置项目
#  servlet:
#    context-path:
spring:
  application:
    name: mall-product
  profiles:
    active: dev
  main: #springboot 2.6.0版本以上开始检查循环依赖 解决 配置如下 或者添加注解 @Lazy
    allow-circular-references: true
  datasource:
    #com.mysql.cj.jdbc.Driver是MySQL 8.0版本中的默认驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/mall-pms
    username: root
    password: root
    # HikariCP 是一个高性能的 JDBC 连接池组件
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接测试query
      connection-test-query: SELECT 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        #指定文件名，没有则默认${spring.application.name}
        #指定文件后缀
        file-extension: yaml
        import-check:
          enabled: false
  jackson: #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
  #thymeleaf 配置
  thymeleaf:
    cache: false
  #redis 配置
  redis:
    host: 192.168.10.100
    port: 6379
    password:     # 密码(默认为空)
    database: 0   #数据库索引 默认为0
    timeout: 60000  # 连接超时时间(毫秒)
    lettuce:
      pool:    # 连接池配置
        enabled: true
        max-active: 8  # 连接池最大连接数(使用负值表示没有限制)
        max-wait: -1   # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接

  session: #整合spring session 解决session统一存储；完成session共享问题
    store-type: redis

  #配置SpringCache
  cache:
    type: redis
    redis:
      time-to-live: 3600000  #默认存活时间
      cache-null-values: true  #是否缓存空值，防止缓存穿透
      use-key-prefix: true  #是否使用 默认true
      #key-prefix: CACHE_  配置会指定缓存前缀

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#线程池配置 MyThreadConfig ThreadPoolConfigProperties
mall:
  thread:
    core-size: 10
    max-size: 100
    keep-alive-time: 10
