#server:
#  port: 30000
#配置项目
#  servlet:
#    context-path:
spring:
#  application:
#    name: mall-third-party
#  profiles:
#    active: dev
  cloud:
    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        #指定文件名，没有则默认${spring.application.name}
        #指定文件后缀
        namespace: 818a32e9-8bc7-44cf-ba21-1c1df7054c7c #命名空间
        group: DEFAULT_GROUP  #默认组

        file-extension: yaml  #DataId的后缀
#        refresh-enabled: true  #是否开启监听和自动刷新默认值true(可以不配置) 如果在这配置了false 下面配置和@RefreshScope不生效
#        import-check:  如果不使用 spring.config.import 设置(如下) spring.cloud.nacos.config.import-check.enabled=false 关闭
#          enabled: false
#  https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
  config:
    import:
      - optional:nacos:application.yaml  # 监听 默认组DEFAULT_GROUP :application.yaml
      - optional:nacos:nacos-discovery.yaml?group=DEFAULT_GROUP  # 覆盖并监听新的组:nacos-discovery.yaml
      - optional:nacos:oss.yaml?group=DEFAULT_GROUP&refreshEnabled=true  # refreshEnabled默认是false 动态刷新

#https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md

#    alicloud:
#      oss:
#        bucket: mys-l
#        endpoint: oss-cn-beijing.aliyuncs.com
#      access-key: XLTAI5tLn2wzbmnwsFySXfVbw
#      secret-key: X1Tr2Zd2vgYn8DoZHpc3FD5yA9bQzgi
#    util:
#      enabled: false #重复注入问题
